version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: eonet_postgres
    environment:
      POSTGRES_DB: eonet_app
      POSTGRES_USER: eonet_user
      POSTGRES_PASSWORD: eonet_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: